### ISSUE TITLE
Its working great. In my case  when mobile is locked  then open  after 10 to 15 mins app restart . android12 

### ISSUE THREAD

**Issue by jainSamy** [joostfunkekupper/background-location-sample-ktx#1]

**Comment by joostfunkekupper** [comment]
I'm glad it is working for you. Are you having any issues?

**Comment by test-adarsh** [comment]
Thanks for response.  i am ruuning this app on android 12  its worked  for sometime  on background mode after 10 to 15 minutes ,I reopen my app its  restart .

**Comment by joostfunkekupper** [comment]
Could you explain in more detail what happens when you reopen the app? Do you mean you lost your data?

**Comment by jainSamy** [comment]
Yes i lost my data. I am getting  the location update  on background mode  and save in realmDatabase .  After  5 to 10 mins services stop .  This problem is occur on 11 and 12 version only
